export const genres = [
  { id: 1, title: '기분 좋을 때' },
  { id: 2, title: '비 오는 날' },
  { id: 3, title: '힙합' },
  { id: 4, title: '케이팝' },
  { id: 5, title: '바나나' },
  { id: 6, title: '오렌지' },
  { id: 7, title: '종교' },
  { id: 8, title: '발라드' },
  { id: 9, title: '바람 부는 날' },
  { id: 10, title: '태풍이 몰아쳐' },
  { id: 11, title: '역주행' },
  { id: 12, title: '카카오톡' },
  { id: 13, title: '라면' },
  { id: 14, title: '블루스' },
  { id: 15, title: '밴드' },
  { id: 16, title: '락' },
  { id: 17, title: '달이 뜬 날' },
  { id: 18, title: '동요' },
  { id: 19, title: '바람 부는 날' },
  { id: 20, title: '잠이 안올 때' },
];
